const EXPO_PUBLIC_API_URI = process.env.EXPO_PUBLIC_API_URI ?? "";
const EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME =
  process.env.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME ?? "";
const EXPO_PUBLIC_CLOUDINARY_API_KEY =
  process.env.EXPO_PUBLIC_CLOUDINARY_API_KEY ?? "";
const EXPO_PUBLIC_CLOUDINARY_API_SECRET =
  process.env.EXPO_PUBLIC_CLOUDINARY_API_SECRET ?? "";
const EXPO_PUBLIC_LIGHTX_API_KEY = process.env.EXPO_PUBLIC_LIGHTX_API_KEY ?? "";

export {
  EXPO_PUBLIC_API_URI,
  EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME,
  EXPO_PUBLIC_CLOUDINARY_API_KEY,
  EXPO_PUBLIC_CLOUDINARY_API_SECRET,
  EXPO_PUBLIC_LIGHTX_API_KEY,
};
