const EXPO_PUBLIC_API_URI = process.env.EXPO_PUBLIC_API_URI ?? "";
const EXPO_PUBLIC_REPLICATE_API_TOKEN =
  process.env.EXPO_PUBLIC_REPLICATE_API_TOKEN ?? "";

export { EXPO_PUBLIC_API_URI, EXPO_PUBLIC_REPLICATE_API_TOKEN };
